lib/mealy_web/router.ex
defmodule MealyWeb.Router do
  use MealyWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :fetch_live_flash
    plug :put_root_layout, {MealyWeb.LayoutView, "root.html"}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  # pipeline :api do
  #   plug :accepts, ["json"]
  # end

  scope "/", MealyWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/dishes", DishController
    resources "/equipment", EquipmentController
    resources "/ingredients", IngredientController

    live "/lists/:id", ListLive, as: :list
    resources "/lists", ListController
    resources "/list_items", ListItemController
    resources "/people", PersonController
    resources "/recipe_ingredients", RecipeIngredientController
    resources "/recipe_sections", RecipeSectionController
    resources "/recipe_steps", RecipeStepController
    resources "/teams", TeamController
  end

  # Other scopes may use custom stacks.
  # scope "/api", MealyWeb do
  #   pipe_through :api
  # end
end

lib/mealy_web/views/layout_view.ex
defmodule MealyWeb.LayoutView do
  use MealyWeb, :view
end

lib/mealy_web/templates/layout/app.html.eex
<%# error messages are persistent %>
<%= if err = get_flash(@conn, :error) do %>
  <p class="ui warning message" role="alert"><%= err %></p>
<% end %>

<%# simple information messages are not %>
<%= if info = get_flash(@conn, :notice) || get_flash(@conn, :info) do %>
<script>
  window.addEventListener('DOMContentLoaded', () => {
    $('body').toast({ message: "<%= Phoenix.HTML.javascript_escape info %>", class: 'black', displayTime: 7000 });
  });
</script>
<% end %>

<%= render(@view_module, @view_template, assigns) %>

lib/mealy_web/templates/layout/root.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>

    <title>Mealy</title>

    <script src="<%= Routes.static_path(@conn, "/js/jquery-3.4.0.js") %>" defer></script>
    <script src="<%= Routes.static_path(@conn, "/js/ckeditor-classic-15.0.0.js") %>" defer></script>

    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>" defer></script>
  </head>

  <body id="mealy-app" class="semantic-ui">
    <nav role="navigation" class="ui stackable inverted fixed main menu mobile hidden">
      <%= link "Mealy", to: "/", class: "header item" %>

      <%= link "Lists", to: Routes.list_path(@conn, :index), class: "item" %>
      <%= link "Dishes", to: Routes.dish_path(@conn, :index), class: "item" %>
      <%= link "Ingredients", to: Routes.ingredient_path(@conn, :index), class: "item" %>
      <%= link "Equipment", to: Routes.equipment_path(@conn, :index), class: "item" %>
      <%= link "People", to: Routes.person_path(@conn, :index), class: "item" %>
    </nav>

    <!-- mobile menu -->
    <div id="mobile-menu" class="slideout-menu slideout-menu-left">
      <div class="ui inverted vertical menu">
        <%= link "Mealy", to: "/", class: "item" %>
        <div class="item"></div>
        <%= link "Lists", to: Routes.list_path(@conn, :index), class: "item" %>
        <%= link "Dishes", to: Routes.dish_path(@conn, :index), class: "item" %>
        <%= link "Ingredients", to: Routes.ingredient_path(@conn, :index), class: "item" %>
        <%= link "Equipment", to: Routes.equipment_path(@conn, :index), class: "item" %>
        <%= link "People", to: Routes.person_path(@conn, :index), class: "item" %>
      </div>
    </div>
    <div id="panel" class="panel slideout-panel slideout-panel-left">
      <div class="ui mobile only">
  			<div class="ui inverted menu">
  				<a class="item mobile-menu-toggle"><i class="bars icon"></i></a>
  			</div>
      </div>
      <div class="mobile hidden" style="height: 40px;"></div>

      <main id="content-container" role="main" class="ui container">
        <%= @inner_content %>
      </main>

      <footer class="ui inverted segment">
        <div id="build-info" class="ui container">
          Mealy <%= Application.get_env(:mealy, :version) %>
          (<%= Application.get_env(:mealy, :build_number) %>) &ndash;
          <%= Timex.format! Application.get_env(:mealy, :release_built_at), "{Mfull} {D}, {YYYY}" %>
        </div>
      </footer>
    </div>
  </body>
</html>